title: "Matt Brown | IT in Animation"
description: "Thoughts, projects, and walkthroughs in animation IT"
baseurl: ""
url: "https://mrbrown89.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

minimal_mistakes_skin: "dark" # Dark mode

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: false

